[package]
name = "resplus-derive"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.39"
syn = { version = "2.0.99", features = ["full"] }
resplus-impl = { path = "../resplus-impl" }

[[test]]
name = "test"
path = "src/tests.rs"

[dev-dependencies]
test-util = { path = "../test-util" }
